### ISSUE TITLE
Handle lambda function invocation with webpack

### ISSUE THREAD

**Issue by amalow** [ConduitVC/aws-utils#30]
Hi There!

I'm currently working on a project using Appsync with Lambda Resolvers written in Typescript (therefore webpack) I've noticed that the Lambda Runner invokes a child process which doesn't work with '.ts' files. I've managed to fix it on my end by manually prepending "./webpack/service" to handlerPath but this is far from the best way to do it. I think the webpack path could be extracted from the serverless configuration (somewhere) but I'm not sure of the best way to integrate it with the rest of the LambdaSource/LambdaRunner.

Another way to fix this would be to exec `serverless invoke local -f ${fn} -d ${payload}` however that's significantly different to the way that child processes are currently being handled.

**Comment by amalow** [comment]
Hi @cbaron 

We use serverless-webpack to handle automatically transpiling our typescript code into Javascript, by default this plugin writes out to `./webpack/service` however that can be configured in the project's webpack config so prepending would not catch all cases if someone had customised their configuration. I'm thinking the best way to do this is to add an option in the project's `serverless.yml` that indicates the executable code directory is different to the default?

Perhaps this is out of the scope of this plugin I'm not too sure.

**Comment by cbaron** [comment]
Got it.  Since we're using [serverless](https://github.com/ConduitVC/aws-utils/blob/master/packages/appsync-emulator-serverless/loadServerlessConfig.js) in our emulator, you should be able to use you're own [variables](https://serverless.com/framework/docs/providers/aws/guide/variables/) when defining the location of your lambda data source.

Let me know if that solves your use case!

**Comment by amalow** [comment]
I've been playing around with this for a little while now, as well as diving into other projects that do something similar like [serverless-offline](https://github.com/dherault/serverless-offline) which seems to use babel to get the output path it looks like. They set the 'location' at startup time. I think this could be done similarly when loading in the serverless config.

This would also enable the opportunity to put in the serverless directory in the config as well. Let me know your thoughts on this. The other way to do this is to use variables however that doesn't seem like as clean of a solution to me as handling would need to be added in `lambdaSource.js` to cater for it.

**Comment by cbaron** [comment]
I'm confused how variables will not give you a clean solution.  Can you give me an explicit example of your ideal use case so that we can implement a solution?

**Comment by amalow** [comment]
I'm happy to put up a PR with an implementation. The variable method I'm suggesting would be something like:

`
custom:
  appsync-offline:
    port: 60004
    modulePrefix: '.webpack/service'
` In serverless.yml

and then in `lambdaSource.js`

`
const lambdaSource = async (
  {
    dynamodbEndpoint,
    dynamodbTables,
    serverlessConfig: { functions, custom },
    serverlessDirectory,
  },
  fn,
  { payload },
) => {
  const fnConfig = functions[fn];
  const [handlerPath, handlerMethod] = fnConfig.handler.split('.');
  let modulePrefix = '';
  if (custom['appsync-offline'] && custom['appsync-offline']['modulePrefix']) {
    modulePrefix = custom['appsync-offline']['modulePrefix'];
  }

  const fullPath = path.join(serverlessDirectory, modulePrefix, handlerPath);
}
`

Let me know what you think of this solution, I'm happy to put a PR up with it if it's acceptable.

**Comment by cbaron** [comment]
Hmm, If I understand your use case correctly, it can be solved by utilizing [environment variables](https://serverless.com/framework/docs/providers/aws/guide/variables#referencing-environment-variables) in serverless.

Please let me know if I'm missing something.

**Comment by amalow** [comment]
Since serverless-offline appends the webpack location to the function handler (see: [index.js](https://github.com/dherault/serverless-offline/blob/master/src/index.js#L360)) using Babel I believe, putting an environment variable in the handler would break functionality with serverless-offline and serverless-webpack.

**Comment by cbaron** [comment]
Ahh, got it, your PR suggestion looks good to me.

**Comment by amalow** [comment]
Closing this as PR is merged in.

**Comment by SET001** [comment]
I may not correct undetstand how it suppose to work but with this config:

```
custom:
  accountId: 565955521116
  appsync-offline:
    port: 60004
    modulePrefix: 'dist/service/'
functions:
  getReservations:
    handler: handler.getReservations
  getTransactions:
    handler: handler.getTransactions
```
i'm getting error in emulator:
```
✖ error Query.getReservations failed
✖ error undefined
```

still, the only way how it does work for me is directly setting path to compiled code:

```
functions:
  getReservations:
    handler: dist/service/src/handler.getReservations
  getTransactions:
    handler: dist/service/src/handler.getTransactions
```
which is not good for me because I can't deploy serverless.yml in such state and I can't push it to git repo...

**Comment by cbaron** [comment]
`appsync-offline` only handles `modulePrefix` -- it does not know what to do with `port`

**Comment by SET001** [comment]
I don't actually use `appsync-offline`. Should I?

**Comment by cbaron** [comment]
Its not necessary.  After looking at your .yml file, I think you should try:

```
custom:
  accountId: 565955521116
  appsync-emulator:
    modulePrefix: dist/service
functions:
  getReservations:
    handler: handler.getReservations
  getTransactions:
    handler: handler.getTransactions
```

Please look at the README!  There is documentation surrounding this feature.
